SET
    FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS pipe_length_status_event;
DROP TABLE IF EXISTS joint_status_event;
DROP TABLE IF EXISTS weld_status_event;
DROP TABLE IF EXISTS cut_list;
DROP TABLE IF EXISTS assembly_list;
DROP TABLE IF EXISTS weld_list;
DROP TABLE IF EXISTS weld;
DROP TABLE IF EXISTS joint;
DROP TABLE IF EXISTS port;
DROP TABLE IF EXISTS fitting;
DROP TABLE IF EXISTS pipe_length;
DROP TABLE IF EXISTS part;
DROP TABLE IF EXISTS spool;
DROP TABLE IF EXISTS isometric;
DROP TABLE IF EXISTS project;
DROP TABLE IF EXISTS user_role;
DROP TABLE IF EXISTS wps;
DROP TABLE IF EXISTS filler_material;
DROP TABLE IF EXISTS diameter;
DROP TABLE IF EXISTS fitting_type;
DROP TABLE IF EXISTS material;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS user;

SET
    FOREIGN_KEY_CHECKS = 1;
